plankiHomePage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'plankiHomePage'

urlpatterns = [
    # Home page url
    path('', views.index, name='index'),

    # Contact page url
    path('contacts/', views.contacts, name='contacts'),

    # Privacy url
    path('privacy/', views.privacy, name='privacy'),

    # Terms url
    path('terms/', views.terms, name='terms'),

    # Feedback url
    path('feedback/', views.feedback, name='feedback'),

    # Products urls
    path('slats/<slug:slug_id>/', views.slats, name='slats'),

    # Detail product url
    path('detail_slats/<slug:slug_id>', views.detail_slats, name='detail_slats'),

    # Authorization
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

    # Settings
    path('settings/', views.settings, name='settings'),

    # Search
    path('search/', views.search, name='search'),

    #Cart
    path('cart/', views.cart, name='cart'),

    #Send data
    path('sendCart/', views.sendCart, name='sendCart')

]

plankiWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # url for admin panel
    path('admin/', admin.site.urls),

    # url for home page
    path('', include('plankiHomePage.urls')),
]

if settings.DEBUG:
    # For 'Debug Toolbar'
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

plankiHomePage/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    email = models.EmailField(verbose_name='Адрес электронной почты', null=True, blank=True, unique=True)
    phone = models.BigIntegerField(verbose_name='Телефонный номер', null=True, blank=True)
    country = models.CharField(max_length=120, verbose_name='Страна', null=True, blank=True)
    region_area = models.CharField(max_length=120, verbose_name='Регион / Область', null=True, blank=True)
    city = models.CharField(max_length=120, verbose_name='Город', null=True, blank=True)
    address1 = models.CharField(max_length=250, verbose_name='Адрес', null=True, blank=True)
    address2 = models.CharField(max_length=250, verbose_name='Дополнительный адрес', null=True, blank=True)
    index = models.BigIntegerField(verbose_name='Индекс', blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['country', 'username']


# class ReviewsSlats(models.Model):
#     user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, verbose_name='Пользователь')
#     product = models.ForeignKey('Slats', on_delete=models.CASCADE, verbose_name='Товар')
#     content = models.CharField(max_length=350, verbose_name='Отзыв')
#     created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
#     updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
#     active = models.BooleanField(default=True, verbose_name='Показывается')
#
#     class Meta:
#         verbose_name = 'Отзыв о планке'
#         verbose_name_plural = 'Отзывы о планках'
#         ordering = ['created', 'product']
#
#     def __str__(self):
#         return f'Комментарий {self.user}'


class CategorySlats(models.Model):
    name = models.CharField(max_length=170, db_index=True, verbose_name='Название')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    slug = models.SlugField(max_length=170, unique=True, verbose_name='Слаг')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорию Планок'
        verbose_name_plural = 'Категории Планок'
        ordering = ['time_create', 'name']

    def get_absolute_url(self):
        return reverse('plankiHomePage:slats', kwargs={'slug_id': self.slug})


class Slats(models.Model):
    category = models.ForeignKey('CategorySlats', on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField(max_length=170, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=170, unique=True, verbose_name='Слаг')
    description = models.TextField(max_length=300, verbose_name='Описание')
    image = models.ImageField(upload_to='plankiHomePage/images/slats/%Y/%m/%d', blank=True, verbose_name='Фото')
    stock = models.PositiveIntegerField(verbose_name='Остаток продукта')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Планка'
        verbose_name_plural = 'Планки'
        ordering = ['time_create', 'name']

    def get_absolute_url(self):
        return reverse('plankiHomePage:detail_slats', kwargs={'slug_id': self.slug})

plankiHomePage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, ReadOnlyPasswordHashField, \
    PasswordChangeForm
from .models import CustomUser
from django.core.exceptions import ValidationError
import re


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=50, label='Имя пользователя')
    password1 = forms.CharField(label='Пароль')
    password2 = forms.CharField(label='Подтвердите пароль')

    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = '__all__'


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', )
    new_password1 = forms.CharField(label='Новый пароль')
    new_password2 = forms.CharField(label='Подтвердите новый пароль')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class CustomSettingsUserForm(forms.ModelForm):
    username = forms.CharField(max_length=150, label='Логин/Никнейм')
    first_name = forms.CharField(required=False, max_length=15, label='Имя')
    last_name = forms.CharField(required=False, max_length=20, label='Фамилия')
    phone = forms.CharField(required=False, min_length=11, max_length=11, label='Телефонный номер')
    email = forms.EmailField(required=False, label='E-Mail')
    country = forms.CharField(required=False, max_length=15, label='Страна')
    region_area = forms.CharField(required=False, max_length=30, label='Регион / Область')
    city = forms.CharField(required=False, max_length=15, label='Город')
    address1 = forms.CharField(required=False, max_length=65, label='Адрес')
    address2 = forms.CharField(required=False, max_length=65, label='Дополнительный адрес')
    index = forms.CharField(required=False, max_length=10, label='Индекс')

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'phone', 'email', 'country', 'region_area', 'city', 'address1',
                  'address2', 'index']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=15, label="Имя ⃰")
    phone = forms.CharField(required=False, min_length=11, max_length=11, label="Номер Телефона")
    email = forms.EmailField(label="Почта ⃰")
    message = forms.CharField(max_length=400, label="Сообщение ⃰")

    def clean_name(self):
        name = self.cleaned_data['name']
        if re.match(r'\d', name):
            raise ValidationError('Имя не должно начинаться с цифры')
        return name

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if re.match(r'\D', phone):
            raise ValidationError('Номер должен соответствовать формату "8 (499) 123-45-67"')
        return phone

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['placeholder'] = self.fields[field].label
        self.fields['message'].widget = forms.Textarea(
            attrs={'class': 'form-control', 'rows': '13', 'placeholder': self.fields['message'].label})

plankiHomePage/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.db.models import *
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import CustomUserCreationForm, UserLoginForm
from django.contrib.auth import login, logout, update_session_auth_hash
from itertools import chain
from django.http import HttpResponse, JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def sendCart(request):
    if request.method == 'POST':
        data_dict = json.loads(request.body)
        print(data_dict)
        return JsonResponse({"success": "Done"})
    else:
        return JsonResponse({"error": "Rong"})


def index(request):
    slats = Slats.objects.filter(
        available=True, category__name='Ордена России')[:6]

    context = {
        'slats': slats,
    }
    return render(request, 'plankiHomePage/index.html', context=context)


def contacts(request):
    return render(request, 'plankiHomePage/contacts.html')


def privacy(request):
    return render(request, 'plankiHomePage/privacy.html')


def terms(request):
    return render(request, 'plankiHomePage/terms.html')


@login_required
def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Отправлено!')
        else:
            messages.error(request, 'Не отправлено')
    else:
        form = FeedbackForm()

    context = {
        'form': form,
    }
    return render(request, 'plankiHomePage/feedback.html', context=context)


# Authorization
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегистрировались!')
            return redirect('plankiHomePage:index')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'plankiHomePage/register.html', context=context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Вы вошли!')
            if request.GET.get('next'):
                return redirect(request.GET.get('next'))
            return redirect('plankiHomePage:index')
        else:
            messages.error(request, 'Ошибка входа')
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }
    return render(request, 'plankiHomePage/login.html', context=context)


@login_required
def user_logout(request):
    logout(request)
    return redirect('plankiHomePage:login')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Пароль был успешно изменён')
            redirect('plankiHomePage:settings')
        else:
            messages.error(request, 'Исправьте ошибки ниже')
    else:
        form = CustomPasswordChangeForm(request.user)

    context = {
        'form': form,
    }
    return render(request, 'plankiHomePage/change_password.html', context=context)


# Settings
@login_required
def settings(request):
    if request.method == 'POST':
        form = CustomSettingsUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Данные изменены!')
            return redirect('plankiHomePage:settings')
    else:
        form = CustomSettingsUserForm(instance=request.user)

    context = {
        'form': form,
    }
    return render(request, 'plankiHomePage/profile_settings.html', context=context)


# Search
def search(request):
    q = request.GET.get('q')

    if q == None:
        q = 'Орден'
    elif q == "":
        q = 'Орден'
    slats = Slats.objects.filter(Q(name__icontains=q) | Q(
        description__icontains=q), Q(available=True))

    # products = sorted(chain(slats, sashes, jettons),
    #                   key=lambda instance: instance.name)

    products = slats
    paginator = Paginator(products, 15)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    context = {
        'q': q,
        'page_obj': page_obj
    }
    return render(request, 'plankiHomePage/search.html', context=context)


# Products
def slats(request, slug_id):
    categories = CategorySlats.objects.annotate(cnt=Count('slats', filter=F('slats__available'))).filter(
        cnt__gt=0).order_by('time_create')
    products = Slats.objects.filter(
        category__slug=slug_id, available=True).order_by('-time_create')
    current_category = CategorySlats.objects.get(slug=slug_id).name
    paginator = Paginator(products, 15)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_num)

    context = {
        'titleForCatalogue': 'Каталог Орденских Планок',
        'categories': categories,
        'page_obj': page_obj,
        'current_category': current_category,
    }
    return render(request, 'plankiHomePage/products.html', context=context)


def sashes(request):
    products = Sashes.objects.filter(available=True).order_by('-time_create')
    paginator = Paginator(products, 15)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_num)

    context = {
        'titleForCatalogue': 'Ленты',
        'page_obj': page_obj,
    }
    return render(request, 'plankiHomePage/products.html', context=context)


def jettons(request):
    products = Jettons.objects.filter(available=True).order_by('-time_create')
    paginator = Paginator(products, 15)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_num)

    context = {
        'titleForCatalogue': 'Жетонны',
        'page_obj': page_obj
    }
    return render(request, 'plankiHomePage/products.html', context=context)


# Detail
def detail_slats(request, slug_id):
    product = get_object_or_404(Slats, slug=slug_id, available=True)

    context = {
        'product': product,
    }
    return render(request, 'plankiHomePage/detail.html', context=context)


def detail_sashes(request, slug_id):
    product = get_object_or_404(Sashes, slug=slug_id, available=True)

    context = {
        'product': product
    }
    return render(request, 'plankiHomePage/detail.html', context=context)


def detail_jettons(request, slug_id):
    product = get_object_or_404(Jettons, slug=slug_id, available=True)

    context = {
        'product': product
    }
    return render(request, 'plankiHomePage/detail.html', context=context)


# Cart
def cart(request):
    cart = None

    context = {
        'cart': cart,
    }
    return render(request, 'plankiHomePage/cart.html', context=context)

plankiHomePage/templates/plankiHomePage/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Корзина :: {{ block.super }}{% endblock %}

{% block content %}
<h2 class="fw-light">Корзина</h1>
    <hr>
    <button type="button" class="btn btn-danger" onclick="clearCart()">Очистить корзину</button>
 {% endblock %}

plankiHomePage/templates/plankiHomePage/change_password.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="fw-light text-center mb-3">Смена пароля</h2>

    <form class="mb-4" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <p class="mb-1">{{ field.label_tag }}</p>
            <p>{{ field }}</p>
            <p>{{ field.errors }}</p>
        {% endfor %}

        <div class="d-grid gap-2 col-md-6 mx-auto">
            <button type="submit" class="btn btn-warning btn-block container-fluid">Сменить Пароль</button>
        </div>
    </form>

{% endblock %}

plankiHomePage/templates/plankiHomePage/contacts.html
{% extends 'base.html' %}

{% block title %}Контакты :: {{ block.super }}{% endblock %}

{% block content %}
<div class ="text-center">
    <h1 class="mb-3 text-center fw-light">Контакты</h1>

    <div class="m-auto bg-warning shadow rounded-3" style="width: 18rem;">
        <h5>Адрес:</h5>
        <p>г.Москва, ул.Фрунзенская набережная д30/2</p>
    </div>

    <hr class="dropdown-divider">

    <div class="m-auto bg-warning shadow rounded-3" style="width: 18rem;">
        <h5>Режим работы:</h5>
        <p>Пн-Сб: с 10:00-20:00<br>Вс: Выходной</p>
    </div>
    <hr class="dropdown-divider">

    <div class="m-auto bg-warning shadow rounded-3"  style="width: 18rem;">
        <h5>Телефон:</h5>
        <p>8-499-391-00-43</p>
    </div>
    <hr class="dropdown-divider">

    <div class="m-auto bg-warning shadow rounded-3" style="width: 18rem;">
        <h5>Email:</h5>
        <p>planki.moskva@mail.ru</p>
    </div>
    <hr class="dropdown-divider">

    <div class="m-auto bg-warning shadow rounded-3" style="width: 18rem;">
        <h5>Мобильный:</h5>
        <p>8-965-296-09-09</p>
    </div>
 </div>
{% endblock %}

plankiHomePage/templates/plankiHomePage/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Подробнее :: {{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-4 align-self-center">
        {% if product.image %}
        <div class="mb-3 text-center">
            <img src="{{ product.image.url }}" width=100% height=100% class="rounded" alt="Image here">
        </div>
        {% else %}
        <div class="mb-3">
            <img src="{% static 'plankiHomePage/images/photo_not_found.png' %}"
                class="rounded border border-1 border-dark" alt="Image here">
        </div>
        {% endif %}
    </div>

    <div class="col align-self-start">
        <h3 class="mb-1 fw-light">{{ product.name }}</h3>
        {% if product.category %}
        <p class="mb-0 fw-light text-muted">Категория: {{ product.category }}</p>
        {% endif %}
        <p class="mb-2 fw-light text-muted">В наличии: {{ product.stock }} шт.</p>
        <h4 class="">{{ product.price|floatformat }}₽</h4>
    </div>
</div>

<!--tabs-->
<nav class="mt-4">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-description-tab" data-bs-toggle="tab" data-bs-target="#nav-description"
            type="button" role="tab" aria-controls="nav-description" aria-selected="true">Описание
        </button>
        <button class="nav-link" id="nav-reviews-tab" data-bs-toggle="tab" data-bs-target="#nav-reviews" type="button"
            role="tab" aria-controls="nav-reviews" aria-selected="false">Отзывы
        </button>
    </div>
</nav>
<div class="tab-content" id="nav-tabContent">
    <div class="mt-1 tab-pane fade show active" id="nav-description" role="tabpanel"
        aria-labelledby="nav-description-tab">{{ product.description }}
    </div>

    <div class="mt-1 tab-pane fade" id="nav-reviews" role="tabpanel" aria-labelledby="nav-reviews-tab">Отзывы
    </div>
</div>

{% endblock %}

plankiHomePage/templates/plankiHomePage/feedback.html
{% extends 'base.html' %}

{% block title %}Обратная связь :: {{ block.super }}{% endblock %}

{% block content %}
    <h1 class="text-center fw-light">Обратная связь</h1>
    <p class="mb-1 text-center">Если Вас заинтересовала деятельность нашего предприятия, возникли вопросы или пожелания,
        предлагаем Вам заполнить данную форму.</p>
    <p class="text-muted text-center">⃰ Поля обязательные для заполнения.</p>

    <form action="{% url 'plankiHomePage:feedback' %}" method="post">

        {% csrf_token %}

        {{ form.non_field_errors }}
        {% for field in form %}
            <div>
                <p>{{ field }}</p>
                <p>{{ field.errors }}</p>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-warning btn-block container-fluid">Отправить</button>
    </form>
{% endblock %}

plankiHomePage/templates/plankiHomePage/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>
        <!-- carousel -->
        <div id="carouselExampleIndicators" class="carousel slide mb-4" data-bs-ride="true">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'plankiHomePage/images/carousel1.jpg' %}" class="d-block w-100" alt="Carousel image">
              </div>
              <div class="carousel-item">
                <img src="{% static 'plankiHomePage/images/carousel2.jpg' %}" class="d-block w-100" alt="Carousel image">
              </div>
              <div class="carousel-item">
                <img src="{% static 'plankiHomePage/images/carousel3.jpg' %}" class="d-block w-100" alt="Carousel image">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Предыдущий</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Следующий</span>
            </button>
          </div>

        <!-- marketing content -->
        <h2 class="mb-1 fw-light">Планки</h2>
        <p class="fw-light">Показываются планки из категории "Ордена России"</p>
        <hr>
        {% include "inc/_products.html" with product_list=slats %}

    </main>
{% endblock %}

plankiHomePage/templates/plankiHomePage/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Авторизация :: {{ block.super }}{% endblock %}
{% block content %}
    <h1>Авторизация</h1>



    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="form-group mb-3">
                <p class="mb-1">{{ field.label_tag }}</p>
                <p>{{ field }}</p>
                <p>{{ field.errors }}</p>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block">Авторизоваться</button>
    </form>
{% endblock %}

plankiHomePage/templates/plankiHomePage/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Товар :: {{ block.super }}{% endblock %}

{% block content %}

    <div class="row row-cols-sm-1 mt-4">

        {# catalogue #}
        {% if categories %}
            <div class="col-12 col-md-3">
                <div class="list-group mb-2 shadow">
                    <li class="list-group-item text-white bg-dark bg-opacity-75" style="text-align: center">
                        <h6 class="mb-0 fw-light">Каталог Орденских Планок</h6>
                    </li>

                    {% for category in categories %}
                        <a class="fw-light list-group-item list-group-item-action {% if category.name == current_category %}bg-secondary text-white{% endif %}"
                           href="{{ category.get_absolute_url }}">
                            {{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {# products #}
        <div class="{% if categories %} col-12 col-md-9 {% else %} col-12 {% endif %}">
            {# current category block #}
            <div>
                <h2 class="fw-light">{% if categories %} {{ current_category }} {% else %}
                    {{ titleForCatalogue }} {% endif %}</h2>
                <hr>
            </div>

            {# products #}
            {% include "inc/_products.html" with product_list=page_obj.object_list %}
        </div>

        {# paginator #}
        {% include "inc/_paginator.html" %}

    </div>

{% endblock %}

plankiHomePage/templates/plankiHomePage/profile_settings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Настройки :: {{ block.super }}{% endblock %}

{% block content %}
    <div>
        <h1 class="text-center fw-light mb-4">Настройки</h1>

        <h2 class="fw-light">Основные</h2>
        <hr>

        <form class="mb-4" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row">
                {% for field in form %}
                    <div class="col-12 col-sm-6">
                        <p class="mb-1">{{ field.label_tag }}</p>
                        <p>{{ field }}</p>
                        <p>{{ field.errors }}</p>
                    </div>
                {% endfor %}
            </div>

            <div class="d-grid gap-2 col-md-6 mx-auto">
                <button type="submit" class="btn btn-warning btn-block  container-fluid">Сохранить</button>
            </div>
        </form>

        <h2 class="fw-light">Смена пароля</h2>
        <hr>

        <a href="{% url 'plankiHomePage:change_password' %}" class="link-dark ">Кликните по этой ссылке для сменны пароля</a>

{#        <form action="{% url 'plankiHomePage:change_password' %}" method="get">#}
{#            <div class="d-grid gap-2 col-md-6 mx-auto">#}
{#                <button type="submit" class="btn btn-warning">Сменить пароль</button>#}
{#            </div>#}
{#        </form>#}

    </div>
{% endblock %}

plankiHomePage/templates/plankiHomePage/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Регистрация :: {{ block.super }}{% endblock %}
{% block content %}
    <h1>Регистрация</h1>



    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="form-group mb-3">
                <p class="mb-1">{{ field.label_tag }}</p>
                <p>{{ field }}</p>
                <p>{{ field.errors }}</p>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block">Регистрация</button>
    </form>
{% endblock %}

plankiHomePage/templates/plankiHomePage/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1 class="mb-3 text-center fw-light">Результат поиска "{{ q }}"</h1>

    {# products #}
    {% include "inc/_products.html" with product_list=page_obj.object_list %}

    {# paginator #}
    {% include 'inc/_paginator.html' %}
{% endblock %}