plankiHomePage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'plankiHomePage'

urlpatterns = [
    # Home page url
    path('', views.index, name='index'),

    # Contact page url
    path('contacts/', views.contacts, name='contacts'),

    # Privacy url
    path('privacy/', views.privacy, name='privacy'),

    # Terms url
    path('terms/', views.terms, name='terms'),

    # Feedback url
    path('feedback/', views.feedback, name='feedback'),

    # Products urls
    path('slats/<slug:slug_id>/', views.slats, name='slats'),

    # Detail product url
    path('detail_slats/<slug:slug_id>', views.detail_slats, name='detail_slats'),

    # Authorization
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

    # Settings
    path('settings/', views.settings, name='settings'),

    # Search
    path('search/', views.search, name='search'),

    #Cart
    path('cart/', views.cart, name='cart'),

    #Send data
    path('sendCart/', views.sendCart, name='sendCart')

]

plankiWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # url for admin panel
    path('admin/', admin.site.urls),

    # url for home page
    path('', include('plankiHomePage.urls')),
]

if settings.DEBUG:
    # For 'Debug Toolbar'
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'plankiHomePage/js/cart.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'plankiHomePage/css/stylesheet.css' %}" rel="stylesheet">
    <title>{% block title %}Планки Москва{% endblock %}</title>
</head>

<body class="bg-light fw-light">

    <!--navbar-->
    <header class="site-header sticky-top">
        <nav class="navbar navbar-expand-xl navbar-dark bg-dark mb-2" style="--bs-bg-opacity: 98%;">
            <div class="container-sm">
                <a class="navbar-brand" href="{% url 'plankiHomePage:index' %}"><img
                        src="{% static 'plankiHomePage/images/logo.png' %}" width="45" height="55" alt="logo here"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link px-2 text-white" href="{% url 'plankiHomePage:slats' slug_id='ordena-rossii' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-award" viewBox="0 0 16 16">
                                    <path
                                        d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z" />
                                    <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z" />
                                </svg>
                                Планки
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'plankiHomePage:cart' %}" class="nav-link px-2 text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-cart3" viewBox="0 0 16 16">
                                    <path
                                        d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg>
                                Корзина
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'plankiHomePage:contacts' %}" class="nav-link px-2 text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-telephone" viewBox="0 0 16 16">
                                    <path
                                        d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                                </svg>
                                Контакты</a>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'plankiHomePage:feedback' %}" class="nav-link px-2 text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-chat-right-text" viewBox="0 0 16 16">
                                    <path
                                        d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z" />
                                    <path
                                        d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                                </svg>
                                Обратная связь</a>
                        </li>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown mb-1">
                            <a class="nav-link dropdown-toggle text-white" id="navbarDropdown2" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-person" viewBox="0 0 16 16">
                                    <path
                                        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                </svg>
                                {{ user.username }}</a>
                            <ul class="dropdown-menu  dropdown-menu-start mb-1" aria-labelledby="navbarDropdown">
                                <li>
                                    <a href="{% url 'plankiHomePage:settings' %}" class="dropdown-item">Настройки</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a href="{% url 'plankiHomePage:logout' %}" class="dropdown-item">Выход</a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown mb-1">
                            <a class="nav-link dropdown-toggle text-white" id="navbarDropdown3" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor"
                                    class="bi bi-person" viewBox="0 0 16 16">
                                    <path
                                        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                </svg>
                                Личный кабинет</a>
                            <ul class="dropdown-menu  dropdown-menu-start mb-1" aria-labelledby="navbarDropdown">
                                <li>
                                    <a href="{% url 'plankiHomePage:register' %}" class="dropdown-item">Регистрация</a>
                                </li>
                                <li>
                                    <a href="{% url 'plankiHomePage:login' %}" class="dropdown-item">Авторизация</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>

                    <form class="d-flex" method="get" action="{% url 'plankiHomePage:search' %}">
                        <input class="form-control me-2" name="q" type="search" placeholder="Поиск по сайту"
                            aria-label="Search">
                        <button class="btn btn-outline-warning" type="submit">Найти</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <!--extends content-->
    <div class="container-sm">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>

    <!--footer-->
    <div class="container-fluid">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom mb-3 fw-light">
                <li class="nav-item"><a href="{% url 'plankiHomePage:index' %}"
                        class="nav-link px-2 text-muted">Главная</a>
                </li>
                <li class="nav-item"><a href="{% url 'plankiHomePage:slats' slug_id='ordena-rossii' %}"
                        class="nav-link px-2 text-muted">Товар</a></li>
                <li class="nav-item"><a href="{% url 'plankiHomePage:contacts' %}"
                        class="nav-link px-2 text-muted">Контакты</a></li>
                <li class="nav-item"><a href="{% url 'plankiHomePage:privacy' %}"
                        class="nav-link px-2 text-muted">Политика
                        безопасности</a></li>
                <li class="nav-item"><a href="{% url 'plankiHomePage:terms' %}" class="nav-link px-2 text-muted">Условия
                        соглашения</a></li>
            </ul>
            <p class="text-center text-muted fw-light">&copy;Интернет-магазин для военнослужащих 2022.</p>
        </footer>
    </div>

    <!--bootstrap scripts-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>